declare const styles: {
    'ms-Label': string;
    app: string;
    top: string;
    bottom: string;
    container: string;
    hideElement: string;
    grid: string;
    row: string;
    column: string;
    'ms-Grid': string;
    title: string;
    subTitle: string;
    description: string;
    profileButton: string;
    button: string;
    'ms-Pivot': string;
    header: string;
    textDialog: string;
    'Card-header': string;
    'CardSub-header': string;
    multiselect: string;
};
export default styles;
